src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProduitRepository::class)
 */
class Produit
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $nom;

    /**
     * @ORM\Column(type="float", nullable=true)
     */
    private $prix;

    /**
     * @ORM\Column(type="array", nullable=true)
     */
    private $liens = [];
    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\ManyToOne(targetEntity=Piece::class, inversedBy="produits")
     */
    private $piece;

    /**
     * @ORM\Column(type="boolean")
     */
    private $achete;

    /**
     * @ORM\Column(type="datetime", nullable=true)
     */
    private $date_achat;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="produits")
     */
    private $user;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $imageUrl;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $uuid;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $commentaire;

    public function __construct()
    {
        $this->created_at = new \DateTime('now');
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(?float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getLiens(): ?array
    {
        return $this->liens;
    }

    public function setLiens(?array $liens): self
    {
        $this->liens = $liens;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getPiece(): ?Piece
    {
        return $this->piece;
    }

    public function setPiece(?Piece $piece): self
    {
        $this->piece = $piece;

        return $this;
    }

    public function getAchete(): ?bool
    {
        return $this->achete;
    }

    public function setAchete(bool $achete): self
    {
        $this->achete = $achete;

        return $this;
    }

    public function getDateAchat(): ?\DateTimeInterface
    {
        return $this->date_achat;
    }

    public function setDateAchat(?\DateTimeInterface $date_achat): self
    {
        $this->date_achat = $date_achat;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getImageUrl(): ?string
    {
        return $this->imageUrl;
    }

    public function setImageUrl(?string $imageUrl): self
    {
        $this->imageUrl = $imageUrl;

        return $this;
    }

    public function getUuid(): ?string
    {
        return $this->uuid;
    }

    public function setUuid(string $uuid): self
    {
        $this->uuid = $uuid;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getCommentaire(): ?string
    {
        return $this->commentaire;
    }

    public function setCommentaire(?string $commentaire): self
    {
        $this->commentaire = $commentaire;

        return $this;
    }
}

templates/pages/creation.html.twig
{% extends 'base.html.twig' %}

{% block body %}
    <div class="container">
        <div class="row mt-5">
            <div class="col">
                <div class="card">
                    <h5 class="card-header">Pièce</h5>
                    <div class="card-body">
                        {{ form_start(pieceForm) }}
                            <div class="form-row">
                                <div class="form-group col-md-6">
                                    <label for="nom_piece">Nom</label>
                                    {{ form_widget(pieceForm.nom, {'attr': {'class': 'form-control'}}) }}
                                </div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="btn btn-rose">Enregistrer</button>
                            </div>
                        {{ form_end(pieceForm) }}
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card">
                    <h5 class="card-header">Produit</h5>
                    <div class="card-body">
                        {{ form_start(produitForm) }}
                        <div class="form-row">
                            <div class="form-group col-md-6">
                                <label for="produit[nom]">Nom</label>
                                {{ form_widget(produitForm.nom, {'attr': {'class': 'form-control'}}) }}
                            </div>
                            <div class="form-group col-md-6">
                                <label for="produit[prix]">Prix approximatif en €</label>
                                {{ form_widget(produitForm.prix, {'attr': {'class': 'form-control'}}) }}
                            </div>
                        </div>
                        <div class="form-group">
                            {{ form_row(produitForm.piece, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            <label for="produit_achete">Acheté ?</label>
                            {{ form_widget(produitForm.achete) }}
                        </div>
                        <div class="form-group">
                            {{ form_row(produitForm.dateAchat, {'attr': {'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            <label for="produit[liens][0]">Lien #1</label>
                            {{ form_widget(produitForm.liens.0, {'attr':{'class': 'form-control'}}) }}
                        </div>
                        <div class="form-group">
                            <label for="produit[liens][1]">Lien #2</label>
                            {{ form_widget(produitForm.liens.1, {'attr':{'class': 'form-control'}}) }}
                        </div>
                        <div class="form-row">
                            <button type="submit" class="btn btn-rose">Enregistrer</button>
                        </div>
                        {{ form_end(produitForm) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

templates/pages/home.html.twig
{% extends 'base.html.twig' %}
{% block body %}
<div class="jumbotron text-center">
    <h1 class="display-4 font-weight-bold">Wishlist</h1>
    <hr class="my-4">
    <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
    <a class="btn btn-rose btn-lg" href="#" role="button">Learn more</a>
</div>
<div class="container">
    <div class="row">
        <div class="w-100 p-3">
            <div class="card-header">
                <h2>Actuelle liste</h2>
                <ul class="list-group">
                    {% for user in users %}
                    <li class="list-group-item">{{ user.email }}</li>
                    {% endfor %}
                </ul>
            </div>
        </div>
    </div>
</div>
{% endblock %}